// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.List;

public class TestUI {

  @Test
  public void untitled() {
    System.setProperty("webdriver.gecko.driver", "geckodriver.exe");
    WebDriver driver = new FirefoxDriver();
    driver.get("https://playground.learnqa.ru/puzzle/triangle");
    {
      List<WebElement> elements = driver.findElements(By.id("show_answ"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("show_answ")).click();
    {
      List<WebElement> elements = driver.findElements(By.linkText("Ссылка на ответы"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.id("hide_answ"));
      assert(elements.size() > 0);
    }
    driver.quit();
  }
}
